#include QMK_KEYBOARD_H

#ifdef CONSOLE_ENABLE
#    include "print.h"
#endif

enum sofle_layers
{
    _QWERTY,
    _COLEMAK,
    _LOWER,
    _RAISE,
    _ACUT,
    _DIAE,
    _ADJUST,
};

enum custom_keycodes
{
    KC_QWERTY = SAFE_RANGE,
    KC_COLEMAK,
    KC_PRVWD,
    KC_NXTWD,
    KC_LSTRT,
    KC_LEND,
    KC_DLINE,
    COMM_SCLN,
    DOT_COLN,
    DEAD_QUOT,
};

#define N_TILD ALGR(KC_N)
#define A_ACUT ALGR(KC_A)
#define E_ACUT ALGR(KC_E)
#define I_ACUT ALGR(KC_I)
#define O_ACUT ALGR(KC_O)
#define U_ACUT ALGR(KC_U)
#define A_DIAE ALGR(KC_Q)
#define O_DIAE ALGR(KC_P)
#define U_DIAE ALGR(KC_Y)

#define SPC_LOW LT(_LOWER, KC_SPC)
#define BSPC_RAI LT(_RAISE, KC_BSPC)

// clang-format off

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ,-----------------------------------------.                ,-----------------------------------------.
 * | = +  | 1 !  | 2 @  | 3 #  | 4 $  | 5 %  |                | 6 ^  | 7 &  | 8 *  | 9 (  | 0 )  | - _  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                |  Y   |  U   |  I   |  O   |  P   | \ |  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | ESC  |  A   |  S   |  D   |  F   |  G   |                |  H   |  J   |  K   |  L   |  Ñ   | ´ ¨  |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |LSFT⇧ |  Z   |  X   |  C   |  V   |  B   | MUTE |  | MPLY |  N   |  M   | , ;  | . :  | / ?  |RSFT⇧ |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |LGUI◆ |LALT⎇ |LCTL⎈ |SPC_LO| DEL  |  |  ⏎   |BSPC_R|RCTL⎈ |AltGr |RGUI◆ |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */

[_QWERTY] = LAYOUT( \
  KC_EQUAL, KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                      KC_6, KC_7, KC_8,      KC_9,     KC_0,     KC_MINUS, \
  KC_TAB,   KC_Q,   KC_W,    KC_E,    KC_R,    KC_T,                      KC_Y, KC_U, KC_I,      KC_O,     KC_P,     KC_BSLASH, \
  KC_ESC,   KC_A,   KC_S,    KC_D,    KC_F,    KC_G,                      KC_H, KC_J, KC_K,      KC_L,     N_TILD,    DEAD_QUOT, \
  KC_LSFT,  KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, KC_MUTE,    KC_MPLY, KC_N, KC_M, COMM_SCLN, DOT_COLN, KC_SLASH, KC_RSFT, \
                 KC_LGUI,KC_LALT,KC_LCTL, SPC_LOW, KC_DEL,      KC_ENT,  BSPC_RAI, KC_RCTL, KC_RALT, KC_RGUI \
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |  `   | 1 !  | 2 @  | 3 #  | 4 $  | 5 %  |                | 6 ^  | 7 &  | 8 *  | 9 (  | 0 )  |  `   |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | ESC  |  Q   |  W   |  F   |  P   |  G   |                |  J   |  L   |  U   |  Y   | : ;  | BSPC |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | TAB  |  A   |  R   |  S   |  T   |  D   |                |  H   |  N   |  E   |  I   |  O   | ' "  |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |LSFT⇧ |  Z   |  X   |  C   |  V   |  B   | MUTE |  |      |  K   |  M   | , <  | . >  | / ?  |RSFT⇧ |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |LGUI◆ |LALT⎇ |LCTL⎈ |SPC_LO|  ⏎   |  | SPC  |BSPC_R|RCTL⎈ |AltGr |RGUI◆ |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */

[_COLEMAK] = LAYOUT( \
  KC_GRV,   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_GRV, \
  KC_ESC,   KC_Q,   KC_W,    KC_F,    KC_P,    KC_G,                      KC_J,    KC_L,    KC_U,    KC_Y, KC_SCLN,  KC_BSPC, \
  KC_TAB,   KC_A,   KC_R,    KC_S,    KC_T,    KC_D,                      KC_H,    KC_N,    KC_E,    KC_I,    KC_O,  KC_QUOT, \
  KC_LSFT,  KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, KC_MUTE,      XXXXXXX,KC_K,    KC_M, KC_COMM,  KC_DOT, KC_SLSH,  KC_RSFT, \
                 KC_LGUI,KC_LALT,KC_LCTL,SPC_LOW, KC_ENT,      KC_SPC,  BSPC_RAI, KC_RCTL, KC_RALT, KC_RGUI \
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |  F1  |  F2  |  F3  |  F4  |  F5  |                |  F6  |  F7  |  F8  |  F9  | F10  | F11  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |  `   | 1 !  | 2 @  | 3 #  | 4 $  | 5 %  |                | 6 ^  | 7 &  | 8 *  | 9 (  | 0 )  | F12  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |  !   |  @   |  #   |  $   |  %   |                |  ^   |  &   |  *   |  (   |  )   |  |   |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |  =   | - _  |  +   |  {   |  }   |      |  |      |  [   |  ]   | : ;  | COLN | \ |  |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_LOWER] = LAYOUT( \
  _______,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                       KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,\
  KC_GRV,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                       KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_F12, \
  _______, KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, KC_PERC,                       KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PIPE, \
  _______,  KC_EQL, KC_MINS, KC_PLUS, KC_LCBR, KC_RCBR, _______,       _______, KC_LBRC, KC_RBRC, KC_SCLN, KC_COLN, KC_BSLS, _______, \
                       _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______\
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |      |      |      |      |      |                |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      | Ins  |PrintS| APP  |      |      |                | PGUP |PRVWD |  UP  |NXTWD |DLINE | BSPC |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |LALT⎇ |LCTL⎈ |LSFT⇧ |      | CAPS |                | PGDN | LEFT | DOWN | RGHT | DEL  | BSPC |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      | UNDO | CUT  | COPY |PASTE |      |      |  |      |      |LSTRT |      | LEND |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_RAISE] = LAYOUT( \
  _______, _______ , _______ , _______ , _______ , _______,                           _______,  _______  , _______,  _______ ,  _______ ,_______, \
  _______,  KC_INS,  KC_PSCR,   KC_APP,  XXXXXXX, XXXXXXX,                        KC_PGUP, KC_PRVWD,   KC_UP, KC_NXTWD,KC_DLINE, KC_BSPC, \
  _______, KC_LALT,  KC_LCTL,  KC_LSFT,  XXXXXXX, KC_CAPS,                       KC_PGDN,  KC_LEFT, KC_DOWN, KC_RGHT,  KC_DEL, KC_BSPC, \
  _______,KC_UNDO, KC_CUT, KC_COPY, KC_PASTE, XXXXXXX,  _______,       _______,  XXXXXXX, KC_LSTRT, XXXXXXX, KC_LEND,   XXXXXXX, _______, \
                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______ \
),


/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |      |      |      |      |      |                |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |      |  É   |      |      |                |      |  Ú   |  Í   |  Ó   |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |  Á   |      |      |      |      |                |      |      |      |      |      | ' "  |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |      |      |      |      |      |      |  |      |      |      |      |      |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_ACUT] = LAYOUT( \
  _______, _______, _______, _______, _______, _______,                         _______, _______, _______, _______, _______, _______, \
  _______, _______, _______, E_ACUT , _______, _______,                         _______, U_ACUT , I_ACUT , O_ACUT , _______, _______, \
  _______, A_ACUT , _______, _______, _______, _______,                         _______, _______, _______, _______, _______, KC_QUOT, \
  _______, _______, _______, _______, _______, _______,     _______,  _______,  _______, _______, _______, _______, _______, _______, \
                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______ \
),

/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |      |      |      |      |      |                |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                |      |  Ü   |      |  Ö   |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |  Ä   |      |      |      |      |                |      |      |      |      |      |  "   |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |      |      |      |      |      |      |  |      |      |      |      |      |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_DIAE] = LAYOUT( \
  _______, _______, _______, _______, _______, _______,                         _______, _______, _______, _______, _______, _______, \
  _______, _______, _______, _______, _______, _______,                         _______, U_DIAE , _______, O_DIAE , _______, _______, \
  _______, A_DIAE , _______, _______, _______, _______,                         _______, _______, _______, _______, _______, S(KC_QUOT), \
  _______, _______, _______, _______, _______, _______,     _______,  _______,  _______, _______, _______, _______, _______, _______, \
                         _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______ \
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |      |      |      |      |      |                |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |RESET |      |QWERTY|COLEMA|CG_TOG|      |                |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |CG_TOG|      |      |      |                |      | VOLD | MUTE | VOLU |      |      |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |      |      |      |      |      |      |  |      |      | MPRV | MPLY | MNXT |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
  [_ADJUST] = LAYOUT( \
  XXXXXXX , XXXXXXX,  XXXXXXX ,  XXXXXXX , XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
  RESET  , XXXXXXX,KC_QWERTY,KC_COLEMAK,CG_TOGG,XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
  XXXXXXX , XXXXXXX,CG_TOGG, XXXXXXX,    XXXXXXX,  XXXXXXX,                     XXXXXXX, KC_VOLD, KC_MUTE, KC_VOLU, XXXXXXX, XXXXXXX, \
  XXXXXXX , XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX,  XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT, XXXXXXX, XXXXXXX, \
                   _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______ \
  )
};
// clang-format on

#ifdef OLED_DRIVER_ENABLE

static void render_logo(void) {
    // clang-format off
    static const char PROGMEM qmk_logo[] = {
        0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,0x90,0x91,0x92,0x93,0x94,
        0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,0xb0,0xb1,0xb2,0xb3,0xb4,
        0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xcb,0xcc,0xcd,0xce,0xcf,0xd0,0xd1,0xd2,0xd3,0xd4,0
    };
    // clang-format on

    oled_write_P(qmk_logo, false);
}

static void print_status_narrow(void) {
    // Print current mode
    oled_write_P(PSTR("\n\n"), false);
    oled_write_ln_P(PSTR("MODE"), false);
    oled_write_ln_P(PSTR(""), false);
    if (keymap_config.swap_lctl_lgui) {
        oled_write_ln_P(PSTR("MAC"), false);
    } else {
        oled_write_ln_P(PSTR("WIN"), false);
    }

    switch (get_highest_layer(default_layer_state)) {
        case _QWERTY:
            oled_write_ln_P(PSTR("Qwrt"), false);
            break;
        case _COLEMAK:
            oled_write_ln_P(PSTR("Clmk"), false);
            break;
        default:
            oled_write_P(PSTR("Undef"), false);
    }
    oled_write_P(PSTR("\n\n"), false);
    // Print current layer
    oled_write_ln_P(PSTR("LAYER"), false);
    switch (get_highest_layer(layer_state)) {
        case _COLEMAK:
        case _QWERTY:
            oled_write_P(PSTR("Base\n"), false);
            break;
        case _RAISE:
            oled_write_P(PSTR("Raise"), false);
            break;
        case _LOWER:
            oled_write_P(PSTR("Lower"), false);
            break;
        case _ACUT:
            oled_write_P(PSTR("Acute"), false);
            break;
        case _DIAE:
            oled_write_P(PSTR("Diae"), false);
            break;
        case _ADJUST:
            oled_write_P(PSTR("Adj\n"), false);
            break;
        default:
            oled_write_ln_P(PSTR("Undef"), false);
    }
    oled_write_P(PSTR("\n\n"), false);
    led_t led_usb_state = host_keyboard_led_state();
    oled_write_ln_P(PSTR("CPSLK"), led_usb_state.caps_lock);
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (is_keyboard_master()) {
        return OLED_ROTATION_270;
    }
    return rotation;
}

void oled_task_user(void) {
    if (is_keyboard_master()) {
        print_status_narrow();
    } else {
        render_logo();
    }
}

#endif

layer_state_t layer_state_set_user(layer_state_t state) { return update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST); }

#ifdef CONSOLE_ENABLE
void oneshot_layer_changed_user(uint8_t layer) {
    uprintf("Oneshot layer %d, %d on\n", layer, (get_mods() & MOD_MASK_SHIFT));
    if (!layer) {
        println("Oneshot layer off");
    }
}
#endif

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    uint16_t masked_keycode = keycode & ~0x1400;

#ifdef CONSOLE_ENABLE
    uprintf("KEYCODE: %d   %b\n", keycode, keycode);
    uprintf("MASKED KEYCODE: %d   %b\n", masked_keycode, masked_keycode);
    uprintf("KC %d %b, MI %d %b, MB %d %b\n", KC_RALT, KC_RALT, MOD_INDEX(KC_RALT), MOD_INDEX(KC_RALT), MOD_BIT(KC_RALT), MOD_BIT(KC_RALT));
    uprintf("IS_KEY: %d   %d\n", IS_KEY(keycode), IS_KEY(masked_keycode));
    uprintf("IS_ANY: %d   %d\n", IS_ANY(keycode), IS_ANY(masked_keycode));
    uprintf("IS_MOD: %d   %d\n", IS_MOD(keycode), IS_MOD(masked_keycode));
    uprintf("\n");
#endif

    // Remix of the behaviour of Spanish and US English keyboards
    // Quote followed by a wovel will add an acute accent to it
    // Similar with double quotes and diaeresis
    // Followed by anything else, will just send the quote or double quotes
    if ((layer_state_is(_ACUT) || layer_state_is(_DIAE)) && IS_KEY(masked_keycode)) {
        if (record->event.pressed) {
            switch (masked_keycode) {
                case KC_A:
                case KC_E:
                case KC_I:
                case KC_O:
                case KC_U:
                case KC_Q:
                case KC_Y:
                case KC_P:
                case KC_QUOT:
                    break;
                default:
                    if (layer_state_is(_DIAE)) {
                        register_mods(MOD_LSFT);
                    }
                    register_code(KC_QUOT);
                    unregister_code(KC_QUOT);
                    if (layer_state_is(_DIAE)) {
                        unregister_mods(MOD_LSFT);
                    }
            }
        }
    }

    uint8_t mod_state = get_mods();
    switch (keycode) {

        case KC_QWERTY:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_QWERTY);
            }
            return false;
        case KC_COLEMAK:
            if (record->event.pressed) {
                set_single_persistent_default_layer(_COLEMAK);
            }
            return false;
        // Invert numbers and symbols on base layers
        case KC_1 ... KC_0:
            if (layer_state_is(_QWERTY) || layer_state_is(_ACUT) || layer_state_is(_DIAE)) {
                if (record->event.pressed) {
                    if (mod_state & MOD_MASK_SHIFT) {
                        del_mods(MOD_MASK_SHIFT);
                        register_code(keycode);
                        set_mods(mod_state);
                    } else {
                        register_mods(MOD_LSFT);
                        register_code(keycode);
                        set_mods(mod_state);
                    }
                } else {
                    unregister_code(keycode);
                }
                return false;
            }
        // Semicolon on shift + comma, like in Spanish keyboards
        case COMM_SCLN:
            if (record->event.pressed) {
                if (mod_state & MOD_MASK_SHIFT) {
                    del_mods(MOD_MASK_SHIFT);
                    register_code(KC_SCLN);
                    set_mods(mod_state);
                } else {
                    register_code(KC_COMM);
                }
            } else {
                unregister_code(KC_SCLN);
                unregister_code(KC_COMM);
            }
            return false;
        // Colon on shift + dot, like in Spanish keyboards
        case DOT_COLN:
            if (record->event.pressed) {
                if (mod_state & MOD_MASK_SHIFT) {
                    register_code(KC_SCLN);
                } else {
                    register_code(KC_DOT);
                }
            } else {
                unregister_code(KC_SCLN);
                unregister_code(KC_DOT);
            }
            return false;
        case KC_PRVWD:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    register_mods(mod_config(MOD_LALT));
                    register_code(KC_LEFT);
                } else {
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_LEFT);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LALT));
                    unregister_code(KC_LEFT);
                } else {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_LEFT);
                }
            }
            break;
        case KC_NXTWD:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    register_mods(mod_config(MOD_LALT));
                    register_code(KC_RIGHT);
                } else {
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_RIGHT);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LALT));
                    unregister_code(KC_RIGHT);
                } else {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_RIGHT);
                }
            }
            break;
        case KC_LSTRT:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    // CMD-arrow on Mac, but we have CTL and GUI swapped
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_LEFT);
                } else {
                    register_code(KC_HOME);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_LEFT);
                } else {
                    unregister_code(KC_HOME);
                }
            }
            break;
        case KC_LEND:
            if (record->event.pressed) {
                if (keymap_config.swap_lctl_lgui) {
                    // CMD-arrow on Mac, but we have CTL and GUI swapped
                    register_mods(mod_config(MOD_LCTL));
                    register_code(KC_RIGHT);
                } else {
                    register_code(KC_END);
                }
            } else {
                if (keymap_config.swap_lctl_lgui) {
                    unregister_mods(mod_config(MOD_LCTL));
                    unregister_code(KC_RIGHT);
                } else {
                    unregister_code(KC_END);
                }
            }
            break;
        case KC_DLINE:
            if (record->event.pressed) {
                register_mods(mod_config(MOD_LCTL));
                register_code(KC_BSPC);
            } else {
                unregister_mods(mod_config(MOD_LCTL));
                unregister_code(KC_BSPC);
            }
            break;
        case KC_COPY:
            if (record->event.pressed) {
                register_mods(mod_config(MOD_LCTL));
                register_code(KC_C);
            } else {
                unregister_mods(mod_config(MOD_LCTL));
                unregister_code(KC_C);
            }
            return false;
        case KC_PASTE:
            if (record->event.pressed) {
                register_mods(mod_config(MOD_LCTL));
                register_code(KC_V);
            } else {
                unregister_mods(mod_config(MOD_LCTL));
                unregister_code(KC_V);
            }
            return false;
        case KC_CUT:
            if (record->event.pressed) {
                register_mods(mod_config(MOD_LCTL));
                register_code(KC_X);
            } else {
                unregister_mods(mod_config(MOD_LCTL));
                unregister_code(KC_X);
            }
            return false;
            break;
        case KC_UNDO:
            if (record->event.pressed) {
                register_mods(mod_config(MOD_LCTL));
                register_code(KC_Z);
            } else {
                unregister_mods(mod_config(MOD_LCTL));
                unregister_code(KC_Z);
            }
            return false;
    }
    return true;
}

void post_process_record_user(uint16_t keycode, keyrecord_t *record) {
    uint8_t mod_state = get_mods();
    switch (keycode) {
        case DEAD_QUOT:
            if (record->event.pressed) {
                if (mod_state & MOD_MASK_SHIFT) {
                    layer_on(_DIAE);
                    set_oneshot_layer(_DIAE, ONESHOT_START);
                } else {
                    layer_on(_ACUT);
                    set_oneshot_layer(_ACUT, ONESHOT_START);
                }
            } else {
                clear_oneshot_layer_state(ONESHOT_PRESSED);
            }
    }
}


#ifdef ENCODER_ENABLE

bool encoder_update_user(uint8_t index, bool clockwise) {
    switch (get_highest_layer(layer_state)) {
        case _COLEMAK:
        case _QWERTY:
            if (index == 0) {
                if (clockwise) {
                    tap_code(KC_MS_WH_RIGHT);
                } else {
                    tap_code(KC_MS_WH_LEFT);
                }
            } else if (index == 1) {
                if (clockwise) {
                    tap_code(KC_MS_WH_UP);
                } else {
                    tap_code(KC_MS_WH_DOWN);
                }
            }
            break;
        case _RAISE:
            if (index == 0) {
                if (clockwise) {
                    tap_code(KC_VOLU);
                } else {
                    tap_code(KC_VOLD);
                }
            } else if (index == 1) {
                if (clockwise) {
                    tap_code(KC_PGDOWN);
                } else {
                    tap_code(KC_PGUP);
                }
            }
            break;
        case _LOWER:
            break;
        case _ADJUST:
            break;
        default:
            break;
    }
    return true;
}

#endif
