[legends]
A_ACUT = Á
A_DIAE = Ä
BSPC_NUM = BSP/NUM
CCED = Ç
COMM_SCLN = , ;
DEAD_QUOT = ´ ¨
DEL_SYM = DEL/SYM
DIV = ÷
DOT_COLN = . :
E_ACUT = É
E_DIAE = Ë
ENT_SYM = ENT/SYM
EUR = €
FORD = ª
I_ACUT = Í
I_DIAE = Ï
IEXCL = ¡
IQUES = ¿
KC_0 = ) 0
KC_1 = ! 1
KC_2 = @ 2
KC_3 = # 3
KC_4 = $ 4
KC_5 = % 5
KC_6 = ^ 6
KC_7 = & 7
KC_8 = * 8
KC_9 = ( 9
KC_AMPR = &
KC_ASTR = *
KC_AT = @
KC_BSLASH = \ |
KC_BSLS = \
KC_CIRC = ^
KC_COLN = :
KC_COMM = ,
KC_DLR = $
KC_DOT = .
KC_DQUO = "
KC_ENT = ⏎
KC_EQL = =
KC_EQUAL = = +
KC_EXLM = !
KC_GRV = `
KC_GT = >
KC_HASH = #
KC_INS = Ins
KC_LALT = LALT⎇
KC_LBRC = [
KC_LCBR = {
KC_LCTL = LCTL⎈
KC_LGUI = LGUI◆
KC_LPRN = (
KC_LSFT = LSFT⇧
KC_LT = <
KC_MINS = -
KC_MINUS = - _
KC_MS_D = MOUSE↓
KC_MS_L = MOUSE←
KC_MS_R = MOUSE→
KC_MS_U = MOUSE↑
KC_NLCK = NumLck
KC_NUBS = \
KC_PAST = P*
KC_PAUSE= Pause
KC_PDOT = P.
KC_PERC = %
KC_PIPE = |
KC_PLUS = +
KC_PMNS = P-
KC_PPLS = P+
KC_PSCR = PrtScr
KC_PSLS = P/
KC_QUES = ?
KC_QUOT = '
KC_QUOTE = ' "
KC_RALT = AltGr
KC_RBRC = ]
KC_RCBR = }
KC_RCTL = RCTL⎈
KC_RGUI = RGUI◆
KC_RPRN = )
KC_RSFT = RSFT⇧
KC_SCLN = ;
KC_SLASH = / ?
KC_SLCK = ScrLck
KC_SLSH = /
KC_TILD = ~
KC_UNDS = _
KC_WBAK = ⯬WBAK
KC_WFWD = ⯮WFWD
KC_WH_D = WHEEL↓
KC_WH_U = WHEEL↑
LDQUO = “
LYRLCK = ESC/LCK
MORD = º
MT_A = A/⇧
MT_C_A = A/⇧
MT_C_E = E/◆
MT_C_I = I/⎈
MT_C_N = N/⎇
MT_C_O = O/⇧
MT_C_R = R/⎈
MT_C_S = S/◆
MT_C_T = T/⎇
MT_D = D/◆
MT_F = F/⎇
MT_J = J/⎇
MT_K = K/◆
MT_L = L/⎈
MT_NT = Ñ/⇧
MT_S = S/⎈
MUL = ×
NEXT_TAB = →TAB
N_TILD = Ñ
O_ACUT = Ó
O_DIAE = Ö
PREV_TAB = ←TAB
PWD_MNGR = PWMNGR
RDQUO = ”
SFT_NUM = SFTNUM
SPC_NAV = SPC/NAV
U_ACUT = Ú
U_DIAE = Ü
UKPND = £
